/**
 * 简化的导出方法（备用方案）
 * 如果 html2canvas 有问题，使用这个方法
 */

/**
 * 方案 A: 打开新窗口让用户手动打印
 */
export function openSlideInNewWindow(slideHTML: string, slideNumber: number) {
  const newWindow = window.open("", `_blank_slide_${slideNumber}`);
  if (!newWindow) {
    throw new Error("Cannot open new window. Please allow popups.");
  }

  newWindow.document.write(slideHTML);
  newWindow.document.close();

  // 等待加载后自动打开打印对话框
  newWindow.onload = () => {
    setTimeout(() => {
      newWindow.print();
    }, 1000);
  };
}

/**
 * 方案 B: 批量打开所有幻灯片到新标签页
 */
export function openAllSlidesForManualExport(
  slides: Array<{ html: string; index: number }>,
) {
  slides.forEach((slide, i) => {
    setTimeout(() => {
      openSlideInNewWindow(slide.html, slide.index + 1);
    }, i * 500); // 每个间隔 500ms 避免浏览器阻止
  });

  alert(
    `Opening ${slides.length} slides in new tabs. Please use Ctrl+P (Cmd+P on Mac) in each tab to save as PDF.`,
  );
}

/**
 * 方案 C: 下载所有 HTML 文件
 */
export async function downloadAllSlidesAsHTML(
  slides: Array<{ html: string; index: number }>,
  title: string,
) {
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();

  slides.forEach((slide) => {
    const filename = `slide-${String(slide.index + 1).padStart(2, "0")}.html`;
    zip.file(filename, slide.html);
  });

  // 添加说明文件
  const readme = `# ${title}

## How to convert to PDF:

1. Open each HTML file in a browser (Chrome recommended)
2. Press Ctrl+P (Windows) or Cmd+P (Mac)
3. Select "Save as PDF"
4. Choose "Landscape" orientation
5. Set margins to "None"
6. Save the file

## Batch conversion:

You can use online tools like:
- https://www.ilovepdf.com/html-to-pdf
- https://cloudconvert.com/html-to-pdf

Or command-line tools like wkhtmltopdf:
\`\`\`bash
wkhtmltopdf --orientation Landscape slide-01.html slide-01.pdf
\`\`\`

Total slides: ${slides.length}
Generated by: Slide Forge AI
`;

  zip.file("README.md", readme);

  const blob = await zip.generateAsync({ type: "blob" });

  // 下载 ZIP
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${title}-html-slides.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * 方案 D: 创建合并的 HTML（所有幻灯片在一个文件中）
 */
export function createCombinedHTML(
  slides: Array<{ html: string; index: number }>,
  title: string,
): string {
  // 提取每个幻灯片的 slide-container 内容
  const slideContents = slides.map((slide) => {
    const match = slide.html.match(
      /<div class="slide-container">([\s\S]*?)<\/div>/,
    );
    return match ? match[1] : "";
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @page {
      size: 1280px 720px;
      margin: 0;
    }
    @media print {
      body { margin: 0; }
      .slide-container {
        page-break-after: always;
        page-break-inside: avoid;
      }
      .slide-container:last-child {
        page-break-after: auto;
      }
    }
    body {
      margin: 0;
      padding: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    }
    .slide-container {
      width: 1280px;
      height: 720px;
      padding: 60px;
      box-sizing: border-box;
      background: white;
      page-break-after: always;
    }
  </style>
</head>
<body>
  ${slides
    .map(
      (slide, i) => `
  <div class="slide-container">
    ${slideContents[i]}
  </div>`,
    )
    .join("\n")}

  <script>
    // 自动打印提示
    window.onload = () => {
      alert('Press Ctrl+P (Cmd+P on Mac) to save as PDF.\\nMake sure to select "Landscape" orientation.');
    };
  </script>
</body>
</html>`;
}

/**
 * 下载合并的 HTML 文件
 */
export function downloadCombinedHTML(
  slides: Array<{ html: string; index: number }>,
  title: string,
) {
  const html = createCombinedHTML(slides, title);

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${title}-complete.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
