/**
 * New presentation types for pure-image mode
 * Each slide is a complete image generated by AI
 */

export interface SlideImage {
  id: string;
  index: number; // Slide number (0-based)
  outlineContent: string; // The outline text for this slide
  imageUrl?: string; // Generated image URL
  status: "pending" | "generating" | "ready" | "error";
  error?: string;

  // Multi-turn conversation history for this slide
  conversationHistory: Array<{
    role: "user" | "assistant";
    parts: Array<{
      text?: string;
      inline_data?: {
        mime_type: string;
        data: string; // base64
      };
    }>;
  }>;

  // Generation metadata
  generatedAt?: Date;
  modificationCount: number; // How many times modified
}

export interface PresentationGenerationState {
  // Generation stage
  stage: "outline" | "generating-slides" | "completed";

  // Current slide being generated/reviewed
  currentSlideIndex: number;

  // All slides (pure images)
  slides: SlideImage[];

  // Outline content (text only)
  outline: string[];

  // Template being used
  templateId: string;
}
